version: '3'
services:
   as-multiply:
          build:
                  context: ./multiply/
                  dockerfile: Dockerfile
   as-summ:
          build:
                  context: ./summ/
                  dockerfile: Dockerfile
   as-sub:
          build:
                  context: ./sub/
                  dockerfile: Dockerfile
   as-control:
          build:
                  context: ./control/
                  dockerfile: Dockerfile
          depends_on:
          - as-multiply  
          - as-summ
          - as-sub

