version: '3'

services:
    ikoskin_server_sinx:
        build:
            context: /home/ikoskin/proekt/server_sinx/
            dockerfile: Dockerfile
    ikoskin_server_plus:
        build:
            context: /home/ikoskin/proekt/server_plus/
            dockerfile: Dockerfile
    control:
        build:
            context: /home/ikoskin/proekt/control/
            dockerfile: Dockerfile
        depends_on:
        - ikoskin_server_sinx
        - ikoskin_server_plus
